# ------ Global -----------------------------------------------------------------
global:
  namespace: amazon-clone

# ------ Image ----------------------------------------------------------------
image:
  repository: vamsibm36
  tag: latest
  pullPolicy: Never             # Never for kind (local), always for EKS

# ------ Secrets ----------------------------------------------------------------
secrets:
  mongoRootUsername: admin
  mongoRootPassword: amazon123
  jwtSecret: super_secret_jwt_key_amazon_clone
  rabbitmqUser: admin
  rabbitmqPassword: amazon123