services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: amazondb
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
    - "6479:6379"