# helm/amazon-clone/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: amazon-mongo-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  MONGO_ROOT_USERNAME: {{ .Values.secrets.mongoRootUsername | b64enc }}
  MONGO_ROOT_PASSWORD: {{ .Values.secrets.mongoRootPassword | b64enc }}
