# k8s/order-service/deployemt.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.orderService.replicas }}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image:  {{ .Values.image.repository }}/amazon-clone-order-service:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.orderService.port }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: amazon-config
                  key: ORDER_SERVICE_PORT
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: amazon-config
                  key: ORDER_SERVICE_MONGO_URI
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: amazon-config
                  key: REDIS_URL
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: amazon-config
                  key: RABBITMQ_URL
          # Uses the /health endpoint your services already expose
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.orderService.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.orderService.port }}
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
