# helm/frontend/Chart.yaml
apiVersion: v2
name: amazon-clone-api-gateway
description: Amazon Clone Microservices Application API Gateway
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - amazon
  - clone
  - microservices
  - helm
  - kubernetes
  - ecommerce
  - api-gateway
maintainers:
  - name: vamsi-b-m
