# ------ Global -----------------------------------------------------------------
global:
  namespace: amazon-clone

# ------ Image ----------------------------------------------------------------
image:
  repository: 071975552330.dkr.ecr.ap-south-1.amazonaws.com/amazon-clone
  tag: api-gateway-1.0.0
  pullPolicy: IfNotPresent             # Never for kind (local), always for EKS

# ------ API Gateway ----------------------------------------------------------------
apiGateway:
  replicas: 1
  port: 4000
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
