# ansible/roles/common/tasks/main.yaml
---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install commmon packages
  apt:
    name:
      - git
      - curl
    state: present

- name: Create app directory
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"
