apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config.yaml
  - secrets.yaml
  - mongo.yaml
  - redis.yaml
  - loki.yaml
  - rabbitmq.yaml
  - ingress.yaml
  - monitoring.yaml
