apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd

  spec:
    project: default
    source:
      repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 7.3.0

      helm:
        values: |
          deploymentMode: SingleBinary

          loki:
            auth_enabled: false

            commonConfig:
              replication_factor: 1

            storage:
              type: filesystem
            
            schemaConfig:
              configs:
                - from: "2024-04-01"
                  store: tsdb
                  object_storage: filesystem
                  schema: v13
                  index:
                    prefix: loki_index_
                    period: 24h
          singleBinary:
            replicas: 1
          
          backend: 
            replicas: 0

          read:
            replicas: 0

          write:
            replicas: 0

          gateway:
            enabled: false

          chunksCache:
            enabled: false

          resultsCache:
            enabled: false

    destination:
      server: https://kubernetes.default.svc
      namespace: monitoring

    syncPolicy:
      automated:
        prune: true
        selfHeal: true

      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
