apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.24.0

    helm:
      values: |
        tempo:
          reportingEnabled: false

          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: "0.0.0.0:4317"
                http:
                  endpoint: "0.0.0.0:4318"
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces
              wal:
                path: /var/tempo/wal

        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClass: gp3
          size: 10Gi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
