# k8s/user-service/service
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: product-service
  ports:
    - name: http
      port: {{ .Values.productService.port }}
      targetPort: {{ .Values.productService.port }}
