# k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: amazon-secret
  namespace: amazon-clone
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: YW1hem9uMTIz
  JWT_SECRET: c3VwZXJfc2VjcmV0X2p3dF9rZXlfYW1hem9uX2Nsb25l
  RABBITMQ_DEFAULT_USER: YWRtaW4=
  RABBITMQ_DEFAULT_PASS:  YW1hem9uMTIz
  RABBITMQ_DEFAULT_PASSWORD: YW1hem9uMTIz
