# ansible/group_vars/all.yml
project_name: amazon-clone
app_dir: /opt/amazon-clone
github_repo: https://github.com/vamsi-b-m/amazon-clone.git
github_branch: dev
dockerhub_username: vamsibm36
compose_file: docker-compose.prod.yaml

# .env variables
env_vars:
  DOCKERHUB_USERNAME: vamsibm36
  DEPLOY_ENV: dev
  MONGO_PORT: "27017"
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: amazon123
  REDIS_PORT: "6379"
  REDIS_URL: redis://redis:6379
  RABBITMQ_PORT_1: "5672"
  RABBITMQ_PORT_2: "15672"
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: amazon123
  RABBITMQ_URL: amqp://admin:amazon123@rabbitmq:5672
  JWT_SECRET: super_secret_jwt_key_amazon_clone
  USER_SERVICE_PORT: "3001"
  USER_SERVICE_URL: http://user-service:3001
  USER_SERVICE_MONGO_URI: mongodb://admin:amazon123@mongo:27017/amazon_users?authSource=admin
  PRODUCT_SERVICE_PORT: "3002"
  PRODUCT_SERVICE_URL: http://product-service:3002
  PRODUCT_SERVICE_MONGO_URI: mongodb://admin:amazon123@mongo:27017/amazon_products?authSource=admin
  CART_SERVICE_PORT: "3003"
  CART_SERVICE_URL: http://cart-service:3003
  CART_SERVICE_MONGO_URI: mongodb://admin:amazon123@mongo:27017/amazon_carts?authSource=admin
  ORDER_SERVICE_PORT: "3004"
  ORDER_SERVICE_URL: http://order-service:3004
  ORDER_SERVICE_MONGO_URI: mongodb://admin:amazon123@mongo:27017/amazon_orders?authSource=admin
  NOTIFICATION_SERVICE_PORT: "3005"
  API_GATEWAY_PORT: "4000"
  FRONTEND_PORT: "80"
  FRONTEND_BIND_PORT: "3000"
