# helm/amazon-clone/values.yaml

# ------ Global -----------------------------------------------------------------
global:
  namespace: amazon-clone

# ------ Secrets ----------------------------------------------------------------
secrets:
  mongoRootUsername: admin
  mongoRootPassword: amazon123
  rabbitmqUser: admin
  rabbitmqPassword: amazon123

# ------ MongoDB ----------------------------------------------------------------
mongo:
  port: 27017

# ------ Redis ----------------------------------------------------------------
redis:
  port: 6379

# ------ RabbitMQ ----------------------------------------------------------------
rabbitmq:
  port: 5672

# ------ User Service ----------------------------------------------------------------
userService:
  port: 3001

# ------ Product Service ----------------------------------------------------------------
productService:
  port: 3002

# ------ Cart Service ----------------------------------------------------------------
cartService:
  port: 3003

# ------ Order Service ----------------------------------------------------------------
orderService:
  port: 3004

# ------ Notification Service ----------------------------------------------------------------
notificationService:
  port: 3005

# ------ API Gateway ----------------------------------------------------------------
apiGateway:
  port: 4000
