# helm/amazon-clone/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: amazon-config
  namespace:  {{ .Values.global.namespace }}
data:
  REDIS_URL: "redis://redis:{{ .Values.redis.port }}"
  RABBITMQ_URL: "amqp://{{ .Values.secrets.rabbitmqUser }}:{{ .Values.secrets.rabbitmqPassword }}@rabbitmq:{{ .Values.rabbitmq.port }}"
  USER_SERVICE_PORT: "{{ .Values.userService.port }}"
  PRODUCT_SERVICE_PORT: "{{ .Values.productService.port }}"
  CART_SERVICE_PORT: "{{ .Values.cartService.port }}"
  ORDER_SERVICE_PORT: "{{ .Values.orderService.port }}"
  NOTIFICATION_SERVICE_PORT: "{{ .Values.notificationService.port }}"
  API_GATEWAY_PORT: "{{ .Values.apiGateway.port }}"
  USER_SERVICE_URL: "http://user-service:{{ .Values.userService.port }}"
  PRODUCT_SERVICE_URL: "http://product-service:{{ .Values.productService.port }}"
  CART_SERVICE_URL: "http://cart-service:{{ .Values.cartService.port }}"
  ORDER_SERVICE_URL: "http://order-service:{{ .Values.orderService.port }}"
  USER_SERVICE_MONGO_URI: "mongodb://{{ .Values.secrets.mongoRootUsername }}:{{ .Values.secrets.mongoRootPassword }}@mongo:{{ .Values.mongo.port }}/amazon_users?authSource=admin"
  PRODUCT_SERVICE_MONGO_URI: "mongodb://{{ .Values.secrets.mongoRootUsername }}:{{ .Values.secrets.mongoRootPassword }}@mongo:{{ .Values.mongo.port }}/amazon_products?authSource=admin"
  CART_SERVICE_MONGO_URI: "mongodb://{{ .Values.secrets.mongoRootUsername }}:{{ .Values.secrets.mongoRootPassword }}@mongo:{{ .Values.mongo.port }}/amazon_carts?authSource=admin"
  ORDER_SERVICE_MONGO_URI: "mongodb://{{ .Values.secrets.mongoRootUsername }}:{{ .Values.secrets.mongoRootPassword }}@mongo:{{ .Values.mongo.port }}/amazon_orders?authSource=admin"
