# helm/amazon-clone/templates/user-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app:  user-service
    {{- include "amazon-clone.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.userService.replicas }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: {{ .Values.image.repository }}/amazon-clone-user-service:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort:  {{ .Values.userService.port }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: amazon-config
                  key:  USER_SERVICE_PORT
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: amazon-config
                  key: USER_SERVICE_MONGO_URI
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: amazon-config
                  key: REDIS_URL
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: amazon-config
                  key: RABBITMQ_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: amazon-secret
                  key: JWT_SECRET
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.userService.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.userService.port }}
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            {{- toYaml .Values.userService.resources | nindent 12 }}
