# k8s/redis/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image:  {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          resources:
            requests:
              memory: {{ .Values.redis.resources.requests.memory }}
              cpu: {{ .Values.redis.resources.requests.cpu }}
            limits:
              memory: {{ .Values.redis.resources.limits.memory }}
              cpu: {{ .Values.redis.resources.limits.cpu }}
