# k8s/user-service/service
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: {{ .Values.apiGateway.port }}
      targetPort: {{ .Values.apiGateway.port }}
