# helm/amazon-clone/values.prod.yaml
image:
  tag: latest
  pullPolicy: Always

userService:
  replicas: 3
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "1000m"

productService:
  replicas: 3

apiGateway:
  replicas: 2

frontend:
  replicas: 2

mongo:
  storage: 10Gi

rabbitmq:
  storage: 5Gi
