apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infrastructure/config.yaml
  - infrastructure/secrets.yaml
  - infrastructure/mongo.yaml
  - infrastructure/redis.yaml
  - infrastructure/rabbitmq.yaml
  - infrastructure/ingress.yaml

  # - applications/api-gateway.yaml
  # - applications/frontend.yaml
  # - applications/user-service.yaml
  # - applications/product-service.yaml
  # - applications/cart-service.yaml
  # - applications/order-service.yaml
  # - applications/notification-service.yaml