# helm/amazon-clone/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: amazon-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  MONGO_ROOT_USERNAME: {{ .Values.secrets.mongoRootUsername | b64enc }}
  MONGO_ROOT_PASSWORD: {{ .Values.secrets.mongoRootPassword | b64enc }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc }}
  RABBITMQ_DEFAULT_USER: {{ .Values.secrets.rabbitmqUser | b64enc }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secrets.rabbitmqPassword | b64enc }}