apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: api-gateway
  namespace: argocd

spec:
  project: default

  sources:

    - repoURL: https://github.com/vamsi-b-m/amazon-clone.git
      targetRevision: dev
      path: helm/applications/api-gateway

      helm:
        valueFiles:
          - $values/environments/dev/applications/api-gateway.yaml

    - repoURL: https://github.com/vamsi-b-m/amazon-clone.git
      targetRevision: dev
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: amazon-clone

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
