# helm/frontend/values.yaml

# ------ Global -----------------------------------------------------------------
global:
  namespace: amazon-clone

# ------ Image ----------------------------------------------------------------
image:
  repository: vamsibm36
  tag: 1.0.0
  pullPolicy: Never             # Never for kind (local), always for EKS

# ------ Frontend ----------------------------------------------------------------
frontend:
  replicas: 1
  port: 80
  resources:
    requests:
      memory: "32Mi"
      cpu: "70m"
    limits:
      memory: "64Mi"
      cpu: "100m"

