# helm/frontend/values.yaml

# ------ Global -----------------------------------------------------------------
global:
  namespace: amazon-clone

# ------ Image ----------------------------------------------------------------
image:
  repository: 071975552330.dkr.ecr.ap-south-1.amazonaws.com/amazon-clone
  tag: frontend-1.0.0
  pullPolicy: IfNotPresent              # Never for kind (local), always for EKS

# ------ Frontend ----------------------------------------------------------------
frontend:
  replicas: 1
  port: 80
  resources:
    requests:
      memory: "32Mi"
      cpu: "70m"
    limits:
      memory: "64Mi"
      cpu: "100m"

