# helm/amazon-clone/values.yaml

# ------ Global -----------------------------------------------------------------
global:
  namespace: amazon-clone

# ------ Image ----------------------------------------------------------------
image:
  repository: vamsibm36
  tag: 2.1.0
  pullPolicy: Never             # Never for kind (local), always for EKS

# ------ User Service ----------------------------------------------------------------
userService:
  replicas: 1
  port: 3001
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"