# k8s/user-service/deployemt.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: amazon-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image:  vamsibm36/amazon-clone-order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: amazon-config
                  key: ORDER_SERVICE_PORT
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: amazon-config
                  key: ORDER_SERVICE_MONGO_URI
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: amazon-config
                  key: REDIS_URL
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: amazon-config
                  key: RABBITMQ_URL
          # Uses the /health endpoint your services already expose
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
