apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ .Release.Name }}
  namespace: monitoring

  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: cart-service

  namespaceSelector:
    matchNames:
      - amazon-clone

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s