# k8s/user-service/service
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: {{ .Values.global.namespace}}
  labels:
    app: cart-service
spec:
  selector:
    app: cart-service
  ports:
    - name: http
      port: {{ .Values.cartService.port }}
      targetPort: {{ .Values.cartService.port }}
