# k8s/user-service/deployemt.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.notificationService.replicas }}
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image:  {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.notificationService.port }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: amazon-config
                  key: NOTIFICATION_SERVICE_PORT
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: amazon-config
                  key: RABBITMQ_URL
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo.monitoring.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "notification-service"
          # Uses the /health endpoint your services already expose
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.notificationService.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.notificationService.port }}
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              memory: {{ .Values.notificationService.resources.requests.memory }}
              cpu: {{ .Values.notificationService.resources.requests.cpu }}
            limits:
              memory: {{ .Values.notificationService.resources.limits.memory }}
              cpu: {{ .Values.notificationService.resources.limits.cpu }}
