name: CD - Deploy

on:
  workflow_run:
    workflows: ["CI - Build and Push Image"]  # must match exactly your CI workflow name
    branches: [main, staging, dev]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to ${{ github.event.workflow_run.head_branch }}
    runs-on: ubuntu-latest

    # Only deploy if CI passed — skip if CI failed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    environment: ${{ github.event.workflow_run.head_branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set image tag
        id: vars
        run: echo "SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Copy prod compose file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "docker-compose.prod.yaml"
          target: "/opt/amazon-clone/"

      - name: Deploy to ${{ github.event.workflow_run.head_branch }} server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /opt/amazon-clone

            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            export IMAGE_TAG=sha-${{ steps.vars.outputs.SHA }}
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}

            docker compose -f docker-compose.prod.yaml pull
            docker compose -f docker-compose.prod.yaml up -d --force-recreate
            docker image prune -f
  