name: CI - Build and Push Image

on:
  push:
    branches: [ main, dev, staging]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_PREFIX: ${{ secrets.DOCKER_USERNAME }}/amazon-clone

jobs:
  build-and-push:
    name: Build and Push - ${{ matrix.service }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - api-gateway
          - user-service
          - product-service
          - cart-service
          - order-service
          - notification-service
          - frontend

      steps:
        # 1. Checkout Code
        - name: Checkout
          uses: actions/checkout@v4
        
        # 2. Login in to Docker Hub
        - name: Login in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        # 3. Extract metadata - generates tags and labels
        - name: Extract metadata
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.IMAGE_PREFIX }}-${{ matrix.service }}
            tags: |
              # tag with branch name: amazon-clone-api-gateway:main
              type=ref,event=branch
              # tag with PR Number: amazon-clone-api-gateway:pr-42
              type=ref,event=pr
              # tag with commit SHA: amazon-clone-api-gateway:sha-a1b2c3d4
              type=ref,prefix=sha-
              # tag latest only on the main branch
              type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
        # 4. Setup Docker Buildx ( enables caching + multi-platform )
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v3

        # 5. Build and Push
        - name: Build and Push ${{ matrix.service }}
          uses: docker/build-push-action@v5
          with:
            context: ${{ matrix.service == 'frontend' && './frontend' || format('./services/{0}', matrix.service )}}
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            # Cache layers between runs - speeds up builds dramatically
            cache-from: type=gha
            cache-to: type=gha, mode=max